export const ERROR_CODES = {
  EMAIL_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  PREMIUM_REQUIRED: "PREMIUM_REQUIRED",
};

// good it's new thing
// for frontend better error handling